# This file was generated by GoReleaser. DO NOT EDIT.
cask "spm" do
  version "0.6.2"

  on_macos do
    on_intel do
      url "https://github.com/decampsrenan/spm/releases/download/v#{version}/spm_#{version}_darwin_amd64.tar.gz"
      sha256 "9cb5169824b20c362f8f87c1eb885f25ff32388058d5ac7780cd027c74bd8177"
    end
    on_arm do
      url "https://github.com/decampsrenan/spm/releases/download/v#{version}/spm_#{version}_darwin_arm64.tar.gz"
      sha256 "53be5e4f8eec2c957230d5217c4e11ed87bc8094dbc7e2deba9ca20aaa9ab97c"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/decampsrenan/spm/releases/download/v#{version}/spm_#{version}_linux_amd64.tar.gz"
      sha256 "4b55ef12437b1da4087347c04ed87d6b8af1743ea5b393362c1d5ff91b926ac6"
    end
    on_arm do
      url "https://github.com/decampsrenan/spm/releases/download/v#{version}/spm_#{version}_linux_arm64.tar.gz"
      sha256 "ae83fb538c5aecffc40707f1559d1a52faa20c868c93cd6fd3970638d43966af"
    end
  end

  name "spm"
  desc "Smart Package Manager — auto-detects and proxies to the right Node.js package manager"
  homepage "https://github.com/decampsrenan/spm"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "spm"

  # No zap stanza required

end
