# This file was generated by GoReleaser. DO NOT EDIT.
cask "spm" do
  name "spm"
  desc "Smart Package Manager — auto-detects and proxies to the right Node.js package manager"
  homepage "https://github.com/decampsrenan/spm"
  version "0.5.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "spm"

  on_macos do
    on_intel do
      url "https://github.com/decampsrenan/spm/releases/download/v#{version}/spm_#{version}_darwin_amd64.tar.gz"
      sha256 "4041c819088a68ab9be4ae9054635b94ef2d572a49f88079552a4f6fb02863d5"
    end
    on_arm do
      url "https://github.com/decampsrenan/spm/releases/download/v#{version}/spm_#{version}_darwin_arm64.tar.gz"
      sha256 "66e797ecbdb31f7873c79b5b8d0bb07ef9fe027c510d54168c1de66746f09128"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/decampsrenan/spm/releases/download/v#{version}/spm_#{version}_linux_amd64.tar.gz"
      sha256 "c8b7886f417b3c3813ff63b84372abad870965cea6af8280d864d5c0f6d18f0a"
    end
    on_arm do
      url "https://github.com/decampsrenan/spm/releases/download/v#{version}/spm_#{version}_linux_arm64.tar.gz"
      sha256 "2222cafc5dfc1f605fa3b48bc6cebdc59fcdc971fdfe84e702cb5291d4f9a6b6"
    end
  end

  # No zap stanza required
end
