# This file was generated by GoReleaser. DO NOT EDIT.
cask "spm" do
  version "0.7.0"

  on_macos do
    on_intel do
      url "https://github.com/decampsrenan/spm/releases/download/v#{version}/spm_#{version}_darwin_amd64.tar.gz"
      sha256 "2a169533d6a88d95c63c483247729ea51b1d3a60ca9b1682fbc0c87f59a3490e"
    end
    on_arm do
      url "https://github.com/decampsrenan/spm/releases/download/v#{version}/spm_#{version}_darwin_arm64.tar.gz"
      sha256 "71acdd2e4d6f40f748da1c2916e527435ef3f2c8fdd8575c109099b8f1181982"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/decampsrenan/spm/releases/download/v#{version}/spm_#{version}_linux_amd64.tar.gz"
      sha256 "c1823d00388303227bd16afc26dd01baaeb281130496ea133296a1165c9658aa"
    end
    on_arm do
      url "https://github.com/decampsrenan/spm/releases/download/v#{version}/spm_#{version}_linux_arm64.tar.gz"
      sha256 "744e0bf19b1772c53fcde4303611067afbcdd196aa9e704eff0317fed5658581"
    end
  end

  name "spm"
  desc "Smart Package Manager — auto-detects and proxies to the right Node.js package manager"
  homepage "https://github.com/decampsrenan/spm"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "spm"

  # No zap stanza required

end
